# R base
FROM r-base

MAINTAINER Bradley R. Jones, BC CfE in HIV/AIDS

# environment variables
ENV BDSRC=/opt/blind-dating

# prerequistes
RUN apt-get update --fix-missing \
  && apt-get install -y \
  zlib1g \
  unzip \
  wget \
  make \
  && rm -rf /var/lib/apt/lists/*

# RAxML
RUN wget -q -O raxml.zip https://github.com/stamatak/standard-RAxML/archive/v8.2.12.zip && \
  unzip raxml.zip -d /tmp && \
  rm raxml.zip
WORKDIR /tmp/standard-RAxML-8.2.12
RUN make -f Makefile.PTHREADS.gcc && \
  rm *.o && \
  ln -s /tmp/standard-RAxML-8.2.12/raxmlHPC-PTHREADS /opt/raxml
  
# CRAN R packages and ggtree
RUN R --vanilla --slave -e 'local({r <- getOption("repos"); r["CRAN"] <- "http://cran.stat.sfu.ca"; options(repos=r)}); install.packages(c("ape", "optparse")); update.packages(ask=FALSE);'

# scripts
COPY src/build.tree.R /opt/blind-dating/
COPY src/raxml.R /opt/blind-dating/

# command
CMD ["Rscript /opt/blind-dating/build.tree.R  --raxml=/opt/raxml8"]