#!/bin/bash

PATID=$1

SRC=/opt/blind-dating
OUTPUT=/mnt/output
INPUT=/mnt/input

INFO=${INPUT}/info_csv
FASTA=${INPUT}/align_fasta
SETTINGS=${INPUT}/settings_txt

mkdir ${OUTPUT}/plots

hostname > ${OUTPUT}/run_info_txt
echo $PATID >> ${OUTPUT}/run_info_txt
date >> ${OUTPUT}/run_info_txt

cd ${OUTPUT} &&
echo 'checking inputs...' &&
Rscript ${SRC}/check.inputs.R --info=${INFO} --fasta=${FASTA} --settings=${SETTINGS} &&
echo 'building tree...' &&
Rscript ${SRC}/build.tree.R --info=${INFO} --fasta=${FASTA} --raxml=/opt/raxml --tree=tree_nwk --settings=${SETTINGS} &&
echo 'rooting tree...' &&
Rscript ${SRC}/root.tree.R --info=${INFO} --tree=tree_nwk --rootedtree=rooted_tree_nwk --settings=${SETTINGS} &&
echo 'regressing...' &&
Rscript ${SRC}/regression.R --patid=${PATID} --training='0' --info=${INFO} --tree=rooted_tree_nwk --stats=stats_csv --data=data_csv --regression=regression_rds --settings=${SETTINGS} &&
Rscript ${SRC}/regression.R --patid=${PATID} --training='-1' --info=${INFO} --tree=rooted_tree_nwk --stats=stats_2_csv --data=data_2_csv --regression=regression_2_rds --settings=${SETTINGS} &&
echo 'plotting...' &&
Rscript ${SRC}/plot.R --patid='plot' --patid2='plot' --info=${INFO} --tree=rooted_tree_nwk --stats=stats_csv --data=data_csv --regression=regression_rds --stats2=stats_2_csv --data2=data_2_csv --regression2=regression_2_rds --statscomb=stats_comb_csv --datacomb=data_comb_csv --settings=${SETTINGS} &&
tar -czf plot_tar_gz plots/*.pdf &&
rm -r plots &&
echo 'done'
