#!/bin/bash

SRC=/opt/blind-dating
OUTPUT=/mnt/output
INPUT=/mnt/input

INFO=${INPUT}/info_csv
FASTA=${INPUT}/align_fasta
SETTINGS=${INPUT}/settings_txt

cd ${OUTPUT} &&
echo 'checking inputs...' &&
Rscript ${SRC}/check.inputs.R --info=${INFO} --fasta=${FASTA} --settings=${SETTINGS} &&
echo 'building tree...' &&
Rscript ${SRC}/build.tree.R --info=${INFO} --fasta=${FASTA} --raxml=/opt/raxml --tree=tree_nwk --settings=${SETTINGS} &&
echo 'rooting tree...' &&
Rscript ${SRC}/root.tree.R --info=${INFO} --tree=tree_nwk --rootedtree=rooted_tree_nwk --settings=${SETTINGS}
echo 'regressing...' &&
Rscript ${SRC}/regression.R --info=${INFO} --tree=rooted_tree_nwk --stats=stats_csv --data=data_csv --regression=regression_rds && --settings=${SETTINGS} &&
echo 'plotting...' &&
Rscript ${SRC}/plot.R --patid='plot' --info=${INFO} --tree=rooted_tree_nwk --stats=stats_csv --data=data_csv --regression=regression_rds --settings=${SETTINGS} &&
tar -czf plot_tar_gz plots/*.pdf &&
rm -r plots &&
echo 'done'
