#!/bin/bash

PATID=$1

SRC=/opt/blind-dating
OUTPUT=/mnt/output
INPUT=/mnt/input

INFO=${INPUT}/info.csv
TREE=${INPUT}/tree.nwk
SETTINGS=${INPUT}/settings.txt

mkdir ${OUTPUT}/plots

hostname > ${OUTPUT}/run_info.txt
echo $PATID >> ${OUTPUT}/run_info.txt
date >> ${OUTPUT}/run_info.txt

cd ${OUTPUT} &&
echo 'checking inputs...' &&
Rscript ${SRC}/check.inputs.R --info=${INFO} --tree=${TREE} --settings=${SETTINGS} &&
echo 'rooting tree...' &&
Rscript ${SRC}/root.tree.R --info=${INFO} --tree=${TREE} --rootedtree=rooted_tree.nwk --settings=${SETTINGS} &&
echo 'regressing...' &&
Rscript ${SRC}/regression.R --patid=${PATID} --info=${INFO} --tree=rooted_tree.nwk --stats=stats.csv --data=data.csv --regression=regression.rds --settings=${SETTINGS} &&
#echo 'plotting...' &&
#Rscript ${SRC}/plot.R --patid='plot' --info=${INFO} --tree=rooted_tree.nwk --stats=stats.csv --data=data.csv --regression=regression.rds --settings=${SETTINGS} &&
tar -czf plot.tar.gz plots/*.pdf &&
rm -r plots &&
echo 'done'
