#!/bin/bash

INFO=$1
FASTA=$2
SETTINGS=$3

SRC=/opt/blind-dating
OUTPUT=/opt/output

cd ${OUTPUT}

Rscript ${SRC}/build.tree.R --info=${INFO} --fasta=${FASTA} --tree=tree_nwk --settings=${SETTINGS}

Rscript ${SRC}/root.tree.R --info=${INFO} --tree=tree_nwk --rootedtree=rooted_tree_nwk --settings=${SETTINGS}

Rscript ${SRC}/regression.R --info=${INFO} --tree=rooted_tree_nwk --stats=stats_csv --data=data_csv --regression=regression_csv --settings=${SETTINGS}

Rscript ${SRC}/plot.R --docker --info=${INFO} --tree=rooted_tree_nwk --settings=${SETTINGS}
